# .github/workflows/activation.yml

name: 1. Get Activation File

on:
  # 手動で実行できるようにする
  workflow_dispatch:

jobs:
  get-activation-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Unity
        uses: actions/cache@v3
        with:
          path: /opt/unity
          key: unity-6000.2.2f1-linux

      - name: Install Unity Hub
        run: |
          wget -qO - https://hub.unity3d.com/linux/keys/public | gpg --dearmor | sudo tee /usr/share/keyrings/Unity_Technologies_ApS.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/Unity_Technologies_ApS.gpg] https://hub.unity3d.com/linux/repos/deb stable main" | sudo tee /etc/apt/sources.list.d/unityhub.list
          sudo apt update
          sudo apt-get install unityhub

      - name: Install Unity Editor
        run: |
          unityhub --headless install --version 6000.2.2f1 --changeset a7a38ad0c740

      - name: Generate activation file
        run: |
          /opt/unity/editors/6000.2.2f1/Editor/Unity -batchmode -createManualActivationFile -quit
          ls -la *.alf

      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: activation-file
          path: "*.alf"