# .github/workflows/activation.yml

name: 1. Get Activation File

on:
  workflow_dispatch:

jobs:
  get-activation-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Request manual activation file
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: StandaloneLinux64
          unityVersion: 6000.2.2f1
          customParameters: -quit -batchmode -nographics -createManualActivationFile

      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: Manual Activation File
          path: "*.alf"